# TrajectoryPlannerROS:
#   max_vel_x: 10.0
#   min_vel_x: 2
#   max_vel_theta: 1.0
#   min_vel_theta: -1.0
#   min_in_place_vel_theta: 0.1
#
#   acc_lim_theta: 2.5
#   acc_lim_x: 5.0
#   acc_lim_y: 5.0
#
#   holonomic_robot: false
#   meter_scoring: true
#
#   # Parameters below can be modified (or add more default parameters) to optimize the local planning.
#   # Use 'rosrun rqt_reconfigure rqt_reconfigure' to dynamically configure during runtime.
#
#   sim_time: 4.0
#   path_distance_bias: 2.0
#   goal_distance_bias: 0.8
#   occdist_scale: 0.5
#
#   vx_samples: 20
#   vtheta_samples: 30
#   heading_lookahead: 0.325
#
#   escape_vel: -1.0



TebLocalPlannerROS:

 odom_topic: /odom
 map_frame: world_enu

 # Tips to reduce CPU usage even further: Impact- (low, medium, high, severe)

 # -Reduce no. of inner and outer iterations (severe)
 # -Keep enable_homotopy_class_planning to false (severe)
 # -Footprint model- avoid large quantity polygons (severe)
 # -Increase dt_ref (<= 0.6) (high)
 # -Reduce obstacle_poses_affected (medium)
 # -Reduce max_number_classes (medium)
 # -Set some unnecessary weigtages to 0 'e.g weight_acc_lim_x' (low)

 # Trajectory

 teb_autosize: True
 dt_ref: 0.5
 dt_hysteresis: 0.06 # Recommended to be >~ 10% dt_ref
 global_plan_overwrite_orientation: True
 allow_init_with_backwards_motion: True
  # Changed from false (steering must be flipped in reversing control)
 max_global_plan_lookahead_dist: 15
 feasibility_check_no_poses: 5
 publish_feedback: False

 # Robot

 max_vel_x: 10
 max_vel_x_backwards: 5
 max_vel_theta: 1
 acc_lim_x: 30
 acc_lim_theta: 1
 min_turning_radius: 4.0 # Changed from 3
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "line"
   radius: 0.2 # for type "circular"
   line_start: [0.0, 0.0] # for type "line"
   line_end: [2.0, 0.0] # for type "line"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 # GoalTolerance

 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.05
 free_goal_vel: True

 # Obstacles

 min_obstacle_dist: 1
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 10
 obstacle_poses_affected: 20
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 # Optimization

 no_inner_iterations: 1
 no_outer_iterations: 1
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1000
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: false
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 1
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
