# Documented by: Jason Han
# School: Monash University Malaysia
# Description: - Parameter file loaded by the navigation stack for costmap parameters shared by the global and local costmap.

# The four parameters below can be configured in rqt_reconfigure (see base_local_planner.yaml) to adjust cost calculations
footprint: [[-1.5, -1], [1.5, -1], [1.5, 1], [-1.5, 1]] # Footprint of the robot
footprint_padding: 0
cost_scaling_factor: 0.55
inflation_radius: 1.5 # Maximum distance from obstacles at which a cost should be incurred

#observation_sources: laser_scan_sensor
#laser_scan_sensor: {sensor_frame: drone_1/LidarCustom, data_type: LaserScan, topic: /LidarCustom/scan, marking: true, clearing: true, inf_is_valid: true}
#subscribe_to_updates: true
#point_cloud_sensor: {sensor_frame: drone_1/LidarCustom, data_type: PointCloud2, topic: /airsim_node/drone_1/lidar/LidarCustom, marking: true, clearing: true}
# ...
obstacle_layer:
  # Set thresholds on obstacle information
  obstacle_range: 20.0 # Maximum range sensor reading that will result in an obstacle being put into the costmap (meters)
  raytrace_range: 20.0 # Determines the range to which we will raytrace freespace given a sensor reading (meters)
  
  track_unknown_space: false
  origin_z: 0
  observation_sources: laser_scan_sensor # A list of sensors that are going to be passing information to the costmap separated by spaces
  laser_scan_sensor:
    sensor_frame: VLP16_1 # Lidar model
    data_type: LaserScan
    topic: /airsim_node/PhysXCar/lidar/VLP16_1/scan # Topic name
    # Add obstacle to the costmap
    marking: true
    # Clear obstacle information from the costmap
    clearing: true
    #inf_is_valid: true
    min_obstacle_height: -10 # Minimum obstacle height from the position of sensor
    max_obstacle_height: 10 # Maximum obstacle height from the position of sensor
  lane: # Lane detection camera
    sensor_frame: front_middle_bumblebee_body 
    data_type: PointCloud
    topic: /lane_points # Topic name
    # Add obstacle to the costmap
    marking: true
    # Clear obstacle information from the costmap
    clearing: true
    min_obstacle_height: -1.5 # Minimum obstacle height from the position of sensor
    max_obstacle_height: 1.5 # Maximum obstacle height from the position of sensor
  depth: # Depth detection camera
    data_type: PointCloud2
    topic: /airsim_node/PhysXCar/front_middle_bumblebee_sync/points # Topic name
    # Add obstacle to the costmap
    marking: true
    # Clear obstacle information from the costmap
    clearing: true
    min_obstacle_height: 0.5 # Minimum obstacle height from the position of sensor
    max_obstacle_height: 1.5 # Maximum obstacle height from the position of sensor

transform_tolerance: 5 # Tolerance of data in meters
