# ...
recovery_behaviors:
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
conservative_reset:
  reset_distance: 0.5
  layer_names: ['obstacle_layer']
aggressive_reset:
  reset_distance: 0.25
  layer_names: ['obstacle_layer']
